version: "3.8"

name: tusq
services:
    server:
        build:
            context: .
            target: final
        ports:
            - 8080:8080
        environment:
            - APP_PORT=${APP_PORT}
            - APP_ENV=${APP_ENV}
            - DB_HOST=db
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - JWT_SECRET=${JWT_SECRET}
        depends_on:
            db:
                condition: service_healthy
        networks:
            - backend
        links:
            - db
    db:
        image: postgres
        restart: always
        user: postgres
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        ports:
            - 5432:5432
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - backend
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    db-data:
networks:
    backend:
